name: Continuous integration example

on: 
  push:
  schedule:
     - cron: '30 12 * * *' # run at 2 AM UTC

      
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn test
